name: Build 🎮

on:
  workflow_run:
    workflows: ["Test ✨"]
    branches: [main]
    types:
      - completed

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:  
  buildWindows:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build for Windows 🖥️
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library
      
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: auto
          targetPlatform: StandaloneWindows64
      
      # Output 
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

#      - name: Zip build
#       run: |
#          pushd build/StandaloneWindows64
#          zip -r ../../StandaloneWindows64.zip .
#          popd
